### ISSUE TITLE
docker-compose up Error

### ISSUE THREAD

**Issue by dale-wahl** [osome-iu/hoaxy-backend#75]
Hello all, I am not sure the docker-compose installation is meant to be used, but after perusing the extensive installation instructions, I thought it couldn't hurt to try! Unfortunately, it doesn't seem to be working and fails on build.

It seems to die on [`RUN conda install -y python=3.7.5\`](https://github.com/IUNetSci/hoaxy-backend/blob/e4c0c2d037d37db21ba5578ecc04992e8bc5f854/docker/Dockerfile#L50) with `OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/conda/lib/python3.10/site-packages/certifi/cacert.pem`. Considering it is a Docker image in process of being built, I'm not sure what is causing `conda` to fail here. Most of the related errors online involve finding where the certs might be, but I'm not sure how to do that while the Docker image is building. I am a bit confused as to why it's checking the python3.10 package for certifi certs when we're explicitly trying to install 3.7.5, but that could be because of what version of conda was just installed in the previous step (it seems to be downgrading 3.10 to 3.7.5 from what I've read).

Regardless, before I take any steps forward, I wanted to confirm that the `docker-compose up` with the docker-compose.yml file was actually supposed to be in working condition. If it was... perhaps you have an idea what my issue is or could even share a working image on Docker Hub? If not, I will take another look at following the step by step manual installation.

Thanks for any help or advise you have!

**Comment by filmenczer** [comment]
This software will no longer be maintained and is being archived. All issues are being closed. Thank you for your understanding.
